### ISSUE TITLE
parse error in filmlists

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#10]
While updating the filmlist with `meth update` I always get parsing errors:

```
Downloading movie list… Exception in thread "main" javax.xml.stream.XMLStreamException: ParseError at [row,col]:[13,136]
Message: The reference to entity "support" must end with the ';' delimiter.
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
        at meth.settings$Settings.$anonfun$listUrl$1(settings.scala:67)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:53)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.movielist$.listUrl$lzycompute(movielist.scala:17)
        at meth.movielist$.listUrl(movielist.scala:17)
        at meth.movielist$.$anonfun$downloadList$1(movielist.scala:95)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:54)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.main$.main(main.scala:34)
        at meth.main.main(main.scala)
```

It does not matter, which filmlist (I tried the one from a fallback url as well), it always crashes like this.

**Comment by eikek** [comment]
Hi @Wurzelmann sorry for the late reply. Interestingly I tried it yesterday on my machine and it works there 🤔 Also my scripts do not report errors so far. Strange! Maybe the file was indeed broken at times? Do you still see the error?

**Comment by Wurzelmann** [comment]
Interestingly enough, this error is gone today, but I've got a new one instead:

```
meth update
Downloading movie list… Exception in thread "main" javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
        at meth.settings$Settings.$anonfun$listUrl$1(settings.scala:67)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:53)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.movielist$.listUrl$lzycompute(movielist.scala:17)
        at meth.movielist$.listUrl(movielist.scala:17)
        at meth.movielist$.$anonfun$downloadList$1(movielist.scala:95)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:54)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.main$.main(main.scala:34)
        at meth.main.main(main.scala)
```

I get this error on both my filmlists:

- https://verteiler1.mediathekview.de/Filmliste-akt.xz
- https://liste.mediathekview.de/Filmliste-akt.xz

**Comment by eikek** [comment]
It still works here… 🤔 I don't have a specific url configured, though. I think the default is https://liste.mediathekview.de/Filmliste-akt.xz

**Comment by Wurzelmann** [comment]
Okay, after restoring a file named `querycmd.scala` (had changes although I've never changed it, pulling the latest code (again) and re-building meth, it works again... :thinking: Thanks for your help!
