### ISSUE TITLE
updating movie list crashes

### ISSUE THREAD

**Issue by Wurzelmann** [eikek/meth#7]
A normal "meth update" does not work anymore and crashes meth as a whole.

Strack trace:

    Downloading movie list… ok
    Unpacking movie list file… Exception in thread "main" org.tukaani.xz.XZFormatException: Input is not in the XZ format
        at org.tukaani.xz.common.DecoderUtil.decodeStreamHeader(Unknown Source)
        at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at meth.movielist$.$anonfun$unpackFile$1(movielist.scala:103)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:54)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.main$.main(main.scala:34)
        at meth.main.main(main.scala)

No changes have been made in the config, has been working for months.

**Comment by eikek** [comment]
Oh that looks like the file is not a xz file. I just tried it here and it works. Could you check the `~/.config/meth` folder? This is the place where the files should be downloaded. There should be a `filmlist.xz` file and the extracted `filmlist` file (no extension). The unix file command should give "XZ compressed data" for the `filmlist.xz` file. Maybe downloading failed in between and the file is corrupted?

**Comment by Wurzelmann** [comment]
Okay, it just worked... after one week with errors and no updates, it did work. Sorry, seems like the movie list had problems, but it is working now.

**Comment by eikek** [comment]
No worries! Glad it's working now. Seems my scripts have luckily skipped the period with the bad filmlist file :-)

**Comment by Wurzelmann** [comment]
Updating the filmlist has not been working for a few days again unfortunately.

```
Downloading movie list… ok
Unpacking movie list file… Exception in thread "main" java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
        at org.tukaani.xz.SingleXZInputStream.readStreamHeader(Unknown Source)
        at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
        at meth.movielist$.$anonfun$unpackFile$1(movielist.scala:103)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:54)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.main$.main(main.scala:34)
        at meth.main.main(main.scala)
```

I tried various sources for the filmlist and even installed the GUI version of mediathekview to check what filmlist file they're using and it's working fine there.

[Source for the GUI version](https://liste.mediathekview.de/Filmliste-akt.xz)

**Comment by eikek** [comment]
Hi, my scripts also broke this morning :-) I think the problem is that meth is not able to follow redirects. The new url redirects to another and the fallback url is not working anymore. As a quick workaround, you could set a working url as fallback in the config:
```
meth {
  fallback-list-url = "https://verteiler3.mediathekview.de/Filmliste-akt.xz"
}
```

**Comment by Wurzelmann** [comment]
Damn, you were faster than me... :-D I just got it to work using *https://verteiler1.mediathekview.de/Filmliste-akt.xz* as fallback, but the not-working redirects would explain this...

If I define multiple fallback-list-urls, is your script able to go through them one by one if any of them aren't working?

**Comment by eikek** [comment]
Unfortunately, no. But this would be a good addition. It already tries a list of urls from here `http://zdfmediathk.sourceforge.net/akt.xml`. This is defined by the setting `current-list-xml`.  One could maintain its own xml file containing a list of urls, but it is not really convenient. I see if the http lib I'm using allows following redirects, then it should be a simple fix.

**Comment by Wurzelmann** [comment]
I saw that too, but the XML file usually contains only one line and yes, maintaining a copy of my own would be an option... thank you for looking into this!

**Comment by eikek** [comment]
Yeah, it's strange that this xml file only contains one line. I'm sure way back then when I wrote it, there were more lines… I guess this is now behind some load balancer node.

**Comment by eikek** [comment]
There is a new version; which works for me :-) If you could verify it, that'd be great. Thank you for reporting and looking into this!

**Comment by Wurzelmann** [comment]
Hm, tried to build the new version, but unfortunately, it did not work:

```
[error] /home/build/meth/src/main/scala/meth/querycmd.scala:10:27: Unused import
[error] import meth.string.syntax._
[error]                           ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 32 s, completed May 11, 2020, 11:08:36 AM
```

I tried *sbt evict* too, but did not change anything.

**Comment by eikek** [comment]
Oh, strange… it compiles here (current master). You could try `sbt clean` to remove any previous artifacts. I uploaded a new version to the release page. Could you try this? I'll take alook into the build issue later.

**Comment by Wurzelmann** [comment]
I tried ```sbt clean```, but it did not change anything. About the release: I'm not sure I understand how to use this. Where is the binary in there?

**Comment by Wurzelmann** [comment]
> I tried `sbt clean`, but it did not change anything. About the release: I'm not sure I understand how to use this. Where is the binary in there?

Oh, I am sorry, I just understood that this IS the binary :-D. Just a second.

**Comment by Wurzelmann** [comment]
I put three fallback urls in my config for testing (your new release) and it seems to work fine! Thank you!

**Comment by Wurzelmann** [comment]
Sorry, have to re-open this one again... the new release seemed to work, but lots of downloads fail (sometimes the filmlist too) with stacktraces like this

```
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
        at scalaj.http.HttpRequest.doConnection(Http.scala:367)
        at scalaj.http.HttpRequest.exec(Http.scala:343)
        at scalaj.http.HttpRequest.asString(Http.scala:492)
        at meth.movielist$.$anonfun$isListCurrent$1(movielist.scala:82)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
        at fs2.internal.Future.step(Future.scala:54)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.runAsync(Future.scala:69)
        at fs2.internal.Future.run(Future.scala:79)
        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
        at meth.main$.main(main.scala:34)
        at meth.main.main(main.scala)
```

Is there any option for increasing verbosity to find out more?

**Comment by eikek** [comment]
Hmm strange again... I don't think there's a setting for verbosity. My scripts worked here after upgrading.... It seems the server refused to connect. I take a look tonight.

Am 11. Mai 2020 12:52:44 MESZ schrieb Wurzelmann <notifications@github.com>:
>Sorry, have to re-open this one again... the new release seemed to
>work, but lots of downloads fail (sometimes the filmlist too) with
>stacktraces like this
>
>```
>Exception in thread "main" java.net.ConnectException: Connection
>refused (Connection refused)
>     at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
>at
>java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
>at
>java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
>at
>java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
>at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
>        at java.base/java.net.Socket.connect(Socket.java:609)
>at
>java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
>   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
>at
>java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
>at
>java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
>at
>java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
>at
>java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
>at
>java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
>at
>java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
>at
>java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
>at
>java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
>at
>java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
>at
>java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
>at
>java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
>at
>java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
>        at scalaj.http.HttpRequest.doConnection(Http.scala:367)
>        at scalaj.http.HttpRequest.exec(Http.scala:343)
>        at scalaj.http.HttpRequest.asString(Http.scala:492)
>        at meth.movielist$.$anonfun$isListCurrent$1(movielist.scala:82)
>at
>scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
>        at fs2.Task$.$anonfun$delay$1(Task.scala:191)
>        at fs2.Task$.$anonfun$suspend$2(Task.scala:199)
>        at fs2.util.Attempt$.apply(Attempt.scala:12)
>        at fs2.Task$.$anonfun$suspend$1(Task.scala:199)
>        at fs2.internal.Future.step(Future.scala:54)
>        at fs2.internal.Future.listen(Future.scala:30)
>        at fs2.internal.Future.runAsync(Future.scala:69)
>        at fs2.internal.Future.run(Future.scala:79)
>        at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14)
>        at meth.main$.main(main.scala:34)
>        at meth.main.main(main.scala)
>```
>
>Is there any option for increasing verbosity to find out more?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eikek/meth/issues/7#issuecomment-626629140

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Wurzelmann** [comment]
> Oh, strange… it compiles here (current master). You could try `sbt clean` to remove any previous artifacts. I uploaded a new version to the release page. Could you try this? I'll take alook into the build issue later.

Btw, I deleted the offending line from the file and it built okay.

**Comment by Wurzelmann** [comment]
> Hmm strange again... I don't think there's a setting for verbosity. My scripts worked here after upgrading.... It seems the server refused to connect. I take a look tonight. Am 11. Mai 2020 12:52:44 MESZ schrieb Wurzelmann <notifications@github.com>:
> […](#)
> Sorry, have to re-open this one again... the new release seemed to work, but lots of downloads fail (sometimes the filmlist too) with stacktraces like this ``` Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused) at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) at java.base/java.net.Socket.connect(Socket.java:609) at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285) at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) at java.base/sun.net.[www.http.HttpClient.openServer(HttpClient.java:474)](http://www.http.HttpClient.openServer(HttpClient.java:474)) at java.base/sun.net.[www.http.HttpClient.openServer(HttpClient.java:569)](http://www.http.HttpClient.openServer(HttpClient.java:569)) at java.base/sun.net.[www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)](http://www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)) at java.base/sun.net.[www.protocol.https.HttpsClient.New(HttpsClient.java:372)](http://www.protocol.https.HttpsClient.New(HttpsClient.java:372)) at java.base/sun.net.[www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)](http://www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)) at java.base/sun.net.[www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)](http://www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)) at java.base/sun.net.[www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)](http://www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)) at java.base/sun.net.[www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)](http://www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)) at java.base/sun.net.[www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)](http://www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)) at java.base/sun.net.[www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)](http://www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) at java.base/sun.net.[www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)](http://www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)) at scalaj.http.HttpRequest.doConnection(Http.scala:367) at scalaj.http.HttpRequest.exec(Http.scala:343) at scalaj.http.HttpRequest.asString(Http.scala:492) at meth.movielist$.$anonfun$isListCurrent$1(movielist.scala:82) at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23) at fs2.Task$.$anonfun$delay$1(Task.scala:191) at fs2.Task$.$anonfun$suspend$2(Task.scala:199) at fs2.util.Attempt$.apply(Attempt.scala:12) at fs2.Task$.$anonfun$suspend$1(Task.scala:199) at fs2.internal.Future.step(Future.scala:54) at fs2.internal.Future.listen(Future.scala:30) at fs2.internal.Future.runAsync(Future.scala:69) at fs2.internal.Future.run(Future.scala:79) at fs2.TaskPlatform$JvmSyntax.unsafeRun(TaskPlatform.scala:14) at meth.main$.main(main.scala:34) at meth.main.main(main.scala) ``` Is there any option for increasing verbosity to find out more? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#7 (comment)](https://github.com/eikek/meth/issues/7#issuecomment-626629140)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

I found out that this is a very specific error for me, it seems. It only occurs when trying to download from ORF servers and only from my IP. 

Different IP + ORF servers = no problem
my normal IP + ORF servers = connection refused
my normal IP + ARTE.DE = no problem.

I apologise for this, as it seems my IP address is currently being blocked by the ORF CDN.

**Comment by eikek** [comment]
No need to apologize! This is really annoying, hope you can workaround this somehow.

**Comment by Wurzelmann** [comment]
Changing the user agent worked. I still don't unterstand why exactly, but it is working again. :-)
